import { Category } from '../types';

export const CATEGORIES: Category[] = [
  {
    id: 'automjete',
    name: 'Automjete',
    icon: 'truck',
    color: '#E74C3C',
    subcategories: ['Makina', 'Motorë', 'Kamionë', 'Pjesë këmbimi', 'Biçikleta'],
    keywords: ['makina', 'makinë', 'makine', 'vetura', 'veturë', 'automjet', 'auto', 'mjet', 'car', 'cars', 'motor', 'motorr', 'skuter', 'kamion', 'furgon', 'xhip', 'suv', 'mercedes', 'audi', 'bmw', 'golf', 'toyota', 'benz', 'goma', 'targa'],
  },
  {
    id: 'prona',
    name: 'Prona',
    icon: 'home',
    color: '#3498DB',
    subcategories: ['Apartamente', 'Shtëpi', 'Tokë', 'Lokale', 'Garazhe'],
    keywords: ['prona', 'pronë', 'shtëpi', 'shtepi', 'shpi', 'shpia', 'shpija', 'apartament', 'banesë', 'banese', 'garsoniere', 'studio', 'vilë', 'vile', 'tokë', 'toke', 'truall', 'oborr', 'lokal', 'dyqan', 'garazh', 'property', 'house', 'home', 'apartment', 'flat'],
  },
  {
    id: 'elektronike',
    name: 'Elektronikë',
    icon: 'monitor',
    color: '#9B59B6',
    subcategories: ['Telefona', 'Laptopë', 'Tableta', 'TV', 'Konsola', 'Aksesorë'],
    keywords: ['elektronik', 'elektronikë', 'telefon', 'celular', 'smartfon', 'smartphone', 'phone', 'iphone', 'samsung', 'xiaomi', 'huawei', 'laptop', 'kompjuter', 'pc', 'desktop', 'tablet', 'monitor', 'tv', 'televizor', 'konsolë', 'konsole', 'playstation', 'ps5', 'xbox', 'kufje', 'pajisje', 'aksesor'],
  },
  {
    id: 'veshje',
    name: 'Veshje & Këpucë',
    icon: 'shopping-bag',
    color: '#E91E63',
    subcategories: ['Për meshkuj', 'Për femra', 'Për fëmijë', 'Këpucë', 'Aksesorë'],
    keywords: ['veshje', 'rroba', 'rrobë', 'fustan', 'bluzë', 'këmishë', 'xhaketë', 'pantallona', 'xhinse', 'kostum', 'këpucë', 'kepuce', 'atlete', 'çizme', 'fashion', 'clothes', 'clothing', 'shoes', 'geta'],
  },
  {
    id: 'shtepi',
    name: 'Për Shtëpinë',
    icon: 'package',
    color: '#FF9800',
    subcategories: ['Mobilje', 'Pajisje kuzhine', 'Dekor', 'Kopsht', 'Vegla pune'],
    keywords: ['shtëpi', 'shtepi', 'mobilje', 'divan', 'kolltuk', 'tavolinë', 'karrige', 'dollap', 'krevat', 'shtrat', 'frigorifer', 'frigo', 'lavatriçe', 'lavatrice', 'enëlarëse', 'sobë', 'mikrovalë', 'kuzhinë', 'dekor', 'kopsht', 'furniture', 'fridge', 'sofa', 'table', 'bed'],
  },
  {
    id: 'pune',
    name: 'Punë',
    icon: 'briefcase',
    color: '#2196F3',
    subcategories: ['Punë me kohë të plotë', 'Punë me kohë të pjesshme', 'Freelance', 'Praktikë'],
    keywords: ['punë', 'pune', 'punësim', 'punetor', 'punëtor', 'job', 'jobs', 'work', 'staf', 'karrierë', 'ofertë'],
  },
  {
    id: 'sherbime',
    name: 'Shërbime',
    icon: 'tool',
    color: '#607D8B',
    subcategories: ['Riparime', 'Pastrim', 'Transport', 'Mësimdhënie', 'IT'],
    keywords: ['shërbim', 'sherbim', 'riparim', 'transport', 'pastrim', 'hidraulik', 'elektricist', 'mësimdhënie', 'mesimdhenie', 'instalim', 'montim', 'service', 'services'],
  },
  {
    id: 'kafshe',
    name: 'Kafshë',
    icon: 'heart',
    color: '#4CAF50',
    subcategories: ['Qen', 'Mace', 'Zogj', 'Peshq', 'Aksesorë kafshësh'],
    keywords: ['kafshë', 'kafshe', 'qen', 'këlysh', 'mace', 'kotele', 'zog', 'peshk', 'pet', 'dog', 'cat', 'animal'],
  },
  {
    id: 'sport',
    name: 'Sport & Hobi',
    icon: 'activity',
    color: '#00BCD4',
    subcategories: ['Pajisje sportive', 'Biçikleta', 'Kamping', 'Instrumente muzikore', 'Libra'],
    keywords: ['sport', 'biçikletë', 'biciklete', 'top', 'mingë', 'palestër', 'pesha', 'fitness', 'kamping', 'çadër', 'kitarë', 'kitare', 'guitar', 'instrument', 'libra', 'hobi', 'ski'],
  },
  {
    id: 'femije',
    name: 'Për Fëmijë',
    icon: 'smile',
    color: '#FF5722',
    subcategories: ['Lodra', 'Veshje fëmijësh', 'Karroca', 'Mobilje fëmijësh'],
    keywords: ['fëmijë', 'femije', 'foshnje', 'bebe', 'lodra', 'lodër', 'karrocë', 'karroce', 'djep', 'baby', 'kids', 'toys', 'toy'],
  },
  {
    id: 'biznes',
    name: 'Biznes & Industri',
    icon: 'trending-up',
    color: '#795548',
    subcategories: ['Pajisje biznesi', 'Material ndërtimi', 'Bujqësi', 'Ushqimore'],
    keywords: ['biznes', 'industri', 'ndërtim', 'ndertim', 'tulla', 'çimento', 'bujqësi', 'fermë', 'ushqimore', 'makineri', 'business', 'material'],
  },
  {
    id: 'te_tjera',
    name: 'Të Tjera',
    icon: 'grid',
    color: '#9E9E9E',
    subcategories: ['Bileta', 'Koleksione', 'Falas', 'Këmbim'],
    keywords: ['të tjera', 'tjera', 'bileta', 'koleksion', 'falas', 'këmbim', 'kembim', 'antike', 'other', 'various'],
  },
];

export const ALBANIAN_CITIES = [
  'Tiranë', 'Durrës', 'Vlorë', 'Elbasan', 'Shkodër',
  'Fier', 'Korçë', 'Berat', 'Lushnjë', 'Pogradec',
  'Kavajë', 'Laç', 'Gjirokastër', 'Sarandë', 'Kukës',
  'Lezhë', 'Peshkopi', 'Burrel', 'Librazhd', 'Përmet',
  'Tepelenë', 'Gramsh', 'Bulqizë', 'Ersekë', 'Krujë',
  'Koplik', 'Pukë', 'Bajzë', 'Rrogozhinë', 'Peqin',
];

export const CONDITION_LABELS: Record<string, string> = {
  'i_ri': 'I Ri',
  'si_i_ri': 'Si i Ri',
  'i_perdorur': 'I Përdorur',
  'per_pjese': 'Për Pjesë',
};
